# Car Price Prediction

In [36]:
# Workflow of Machine Learning Model
'''
0) Import Important dependencies
1) Setting up the data
2) Creating the Model
3) Training the Model
4) Testing the Model
5) Prediction
'''

'\n0) Import Important dependencies\n1) Setting up the data\n2) Creating the Model\n3) Training the Model\n4) Testing the Model\n5) Prediction\n'

## 1. Import libraries

In [37]:
# Importing Important Dependencies
import numpy as np
import pandas as pd

In [38]:
# Importing LinearRegression Model(to predict continuous values)
from sklearn.linear_model import LinearRegression

In [39]:
# Importing train test split function
from sklearn.model_selection import train_test_split

In [40]:
# Importing Accuracy score
from sklearn import metrics

## 2. Load Dataset

In [41]:
# Import dataset
df = pd.read_csv('cardata.csv')
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

## 3. Data preprocessing

In [44]:
# Info of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [45]:
# Checking null values
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [46]:
# Basic analysis
# Find the unique values under Fuel_Type, Seller_Type, Transmission
print(pd.unique(df['Fuel_Type']))
print(pd.unique(df['Seller_Type']))
print(pd.unique(df['Transmission']))

['Petrol' 'Diesel' 'CNG']
['Dealer' 'Individual']
['Manual' 'Automatic']

In [47]:
# Feature Encoding --> converting non-numerical categorical data 
# (e.g., labels, names, types) into a numerical format
df.replace({'Fuel_Type': {'Petrol': 0, 'Diesel': 1, 'CNG': 2}}, inplace = True)
df.replace({'Seller_Type': {'Dealer': 0, 'Individual': 1}}, inplace = True)
df.replace({'Transmission': {'Manual': 0, 'Automatic': 1}}, inplace = True)

C:\Users\Balamurugan\AppData\Local\Temp\ipykernel_31536\571949050.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'Fuel_Type': {'Petrol': 0, 'Diesel': 1, 'CNG': 2}}, inplace = True)
C:\Users\Balamurugan\AppData\Local\Temp\ipykernel_31536\571949050.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'Seller_Type': {'Dealer': 0, 'Individual': 1}}, inplace = True)
C:\Users\Balamurugan\AppData\Local\Temp\ipykernel_31536\571949050.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'Transmission': {'Manual': 0, 'Automatic': 1}}, inplace = True)

In [48]:
# Input Feature - X
# Target feature - Y
X = df.drop(['Car_Name','Selling_Price'], axis = 1)
Y = df['Selling_Price']

In [49]:
X

,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,5.59,27000,0,0,0,0
1,2013,9.54,43000,1,0,0,0
2,2017,9.85,6900,0,0,0,0
3,2011,4.15,5200,0,0,0,0
4,2014,6.87,42450,1,0,0,0
...,...,...,...,...,...,...,...
296,2016,11.60,33988,1,0,0,0
297,2015,5.90,60000,0,0,0,0
298,2009,11.00,87934,0,0,0,0
299,2017,12.50,9000,1,0,0,0
300,2016,5.90,5464,0,0,0,0

In [50]:
Y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

## 4. Train-test split

In [60]:
# Splitting the data into Training and Testing Data
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 42)

In [61]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(301, 7)
(240, 7)
(61, 7)

## 5. Model Trainig

In [62]:
# Model Training
model = LinearRegression()

In [63]:
# Training the ML model with training data
model.fit(X_train, Y_train)

LinearRegression()

## 6. Model Evaluation

In [64]:
# Prediction of Training data
training_data_prediction = model.predict(X_train)
# Finding accracy score of training data
training_data_accuracy = metrics.r2_score(Y_train, training_data_prediction)
print("Accuracy score of training data is", training_data_accuracy)

Accuracy score of training data is 0.8839793496750794

In [65]:
# Prediction of Testing data
testing_data_prediction = model.predict(X_test)
# Finding accracy score of testing data
testing_data_accuracy = metrics.r2_score(Y_test, testing_data_prediction)
print("Accuracy score of testing data is", testing_data_accuracy)

Accuracy score of testing data is 0.8468053957654722

In [66]:
# Builiding a predictive system
input_data = (2011,0.826,6000,0,1,0,0)
input_data_array = np.asarray(input_data)
# Reshape to one data point
input_data_reshape = input_data_array.reshape(1,-1)

## 7. Prediction

In [67]:
# Prediction
prediction = model.predict(input_data_reshape)
print('Selling price of the vehicle is', prediction)

Selling price of the vehicle is [-0.27682137]

C:\Users\Balamurugan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(